[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brocode"
version = "0.2.0"
description = "brocode is a lightweight coding assistant in CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "broflow>=0.2.0",
    "brollm>=0.2.0",
]


[dependency-groups]
dev = [
    "boto3>=1.43.93",
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    "requests>=2.34.2",
]
