default_model: openai-oss-20b
models:
  llama3.2-11b: /Users/pathompolnilchaikovit/Desktop/projects/brocode/mylocal.py
  openai-oss-20b: /Users/pathompolnilchaikovit/Desktop/projects/brocode/mylocal.py
